[package]
name = "rust_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "rust_test"
path = "src/main.rs"

[lib]
name = "rust_test_lib"
path = "src/lib.rs"
